# create deployment in the first half.. the next half is creating the service.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-deployment
  labels:
    app: capstone
spec:
  replicas: 1
  selector:
  # select pod based on its label
    matchLabels:
      app: capstone-pod
  template:
    metadata:
      labels:
        app: capstone-pod
    spec:
      containers:
      - name: capstone-container
        image: gaganmahesh2021/capstone2
        ports:
        - containerPort: 80
---
  apiVersion: v1
  kind: Service
  metadata:
    name: capstone-service
  spec:
    selector:
      app: capstone-pod
    type: LoadBalancer
    ports:
      - protocol: TCP
        port: 80
        targetPort: 80
        nodePort: 30000

